#if !canImport(ObjectiveC)
import XCTest

extension ProtocolTypeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProtocolTypeTests = [
        ("testTypeIsResolved", testTypeIsResolved),
        ("testWrongTypeIsNil", testWrongTypeIsNil),
    ]
}

extension ValuePointersTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValuePointersTests = [
        ("testBytesAreCorrect", testBytesAreCorrect),
    ]
}

extension VisitorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VisitorTests = [
        ("testVisitDecodableType", testVisitDecodableType),
        ("testVisitHashable", testVisitHashable),
//        ("testVisitView", testVisitView),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ProtocolTypeTests.__allTests__ProtocolTypeTests),
        testCase(ValuePointersTests.__allTests__ValuePointersTests),
        testCase(VisitorTests.__allTests__VisitorTests),
    ]
}
#endif
